services:
  pzserver:
    build:
      context: ./pzserver
      dockerfile: Dockerfile
    container_name: pzserver
    image: localhost/pzserver:latest
    ports:
    - 16261:16261/udp
    - 16262:16262/udp
    - 27015:27015/tcp
    restart: unless-stopped
    stop_grace_period: 60s
    volumes:
    - pz-zomboid:/home/steam/Zomboid
    - pz-steamapps:/opt/pzserver/steamapps
    - ./servertest.ini:/home/steam/Zomboid/Server/servertest.ini:ro,z
  pzsm:
    build:
      context: ./pzsm
      dockerfile: Dockerfile
    container_name: pzsm
    depends_on:
      pzserver:
        condition: service_started
    expose:
    - '8080'
    image: localhost/pzsm:latest
    restart: unless-stopped
    stop_grace_period: 10s
    volumes:
    - pz-zomboid:/var/lib/pzserver
    - ./pzsm/config.yaml:/etc/pzsm/config.yaml:rw,z
    - ./pzsm.db:/var/lib/pzsm/pzsm.db:rw,z
    - ./servertest.ini:/var/lib/pzsm/servertest.ini:rw,z
  pzsmui:
    build:
      context: ./pzsmui
      dockerfile: Dockerfile
    container_name: pzsmui
    depends_on:
      pzsm:
        condition: service_started
    expose:
    - '80'
    image: localhost/pzsmui:latest
    restart: unless-stopped
volumes:
  pz-steamapps: null
  pz-zomboid: null